config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  root to: "home#index"
  get "users/me" => "users#me"
  resources :users do 
  	member do
  		get 'widgets'
  	end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :widgets
end

app/models/widget.rb
# frozen_string_literal: true

class Widget
  include Api::Builder

  attr_accessor :id, :name, :description, :kind, :user, :owner

  def attributes
    {
      name: nil,
      description: nil,
      kind: nil
    }
  end

  def self.all(type, term = '', current_user)
    if type == 'visible'
      response = execute(:get, "/api/v1/widgets/visible?term=#{term}&client_id=#{ENV['CLIENT_ID']}&client_secret=#{ENV['CLIENT_SECRET']}", {})
    else
      response = execute(:get, '/api/v1/widgets', current_user.serializable_hash)
    end

    widgets = response[:data][:widgets].map { |widget| Widget.new(widget) }
    widgets
  rescue RestClient::UnprocessableEntity => e
    false
  end

  def self.all_by_user(id, term = '', current_user)
    response = execute(:get, "/api/v1/users/#{id}/widgets?term=#{term}&client_id=#{ENV['CLIENT_ID']}&client_secret=#{ENV['CLIENT_SECRET']}", {}, { "Authorization": "Bearer #{current_user.access_token}" })
    widgets = response[:data][:widgets].map { |widget| Widget.new(widget) }
    widgets
  rescue RestClient::UnprocessableEntity => e
    []
  end

  def save(current_user)
    if id.present?
      response = self.class.execute(:put, "/api/v1/widgets/#{id}", { widget: serializable_hash }, { "Authorization": "Bearer #{current_user.access_token}" })
    else
      response = self.class.execute(:post, '/api/v1/widgets', { widget: serializable_hash }, { "Authorization": "Bearer #{current_user.access_token}" })
      self.id = response[:id]
    end
    response
    # rescue RestClient::UnprocessableEntity => exception
    # return false
  end

  def self.destroy(current_user, id)
    response = execute(:delete, "/api/v1/widgets/#{id}", { "Authorization": "Bearer #{current_user.access_token}" })
    response
  rescue RestClient::UnprocessableEntity => e
  end
end

app/controllers/widgets_controller.rb
# frozen_string_literal: true

class WidgetsController < ApplicationController
  before_action :authenticate_user

  def new
    @widget = Widget.new
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)
    respond_to do |format|
      response = @widget.save(current_user)
      if response
        format.html { redirect_to root_path, notice: 'Widget created successfully' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @widget = Widget.new(widget_params)
    @widget.id = params[:id]
    respond_to do |format|
      response = @widget.save(current_user)
      if response
        format.html { redirect_to request.referer, notice: 'Widget updated successfully' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    response = Widget.destroy(current_user, params[:id])
    redirect_to request.referer
  end

  private

  def widget_params
    params.require(:widget).permit(:description, :name, :id, :kind)
  end
end

app/helpers/widget_helper.rb
module WidgetHelper
end

app/views/widgets/_form.html.erb
<%= simple_form_for(widget, wrapper: :vertical_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :description, required: true %>
  	<%= f.input :kind, :collection => [['visible','visible'],['hidden', 'hidden']], required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-primary" %>
  </div>
<% end %>

app/views/widgets/_list.html.erb
<% @widgets.each do |widget| %>
	<tr>
	  <td><%= widget.name%></td>
	  <td><%=widget.description%></td>
	   <td><a href=<%= "/users/#{widget.user[:id]}/widgets"%> class="card-link"><%= image_tag widget.user[:images][:small_url], class: "img-circle", height:"30", width:"30" %><%= widget.user[:name]%></a></td>
	   
	  <td>
	  	<% if widget.owner %>
		  	<button class = "btn btn-primary" data-toggle="modal" data-target = <%= "#widgetEditModal#{widget.id}"%> >Edit</button>
					<div class="container">
					  <!-- The Modal -->
					  <div class="modal" id=<%="widgetEditModal#{widget.id}"%>>
					    <div class="modal-dialog">
					      <div class="modal-content">
					      
					        <!-- Modal Header -->
					        <div class="modal-header">
					          <h4 class="modal-title">Widget</h4>
					          <button type="button" class="close" data-dismiss="modal">&times;</button>
					        </div>
					        
					        <!-- Modal body -->
					        <div class="modal-body">
										<%= simple_form_for(widget, :url => widget_path(widget.id), method: :put, wrapper: :vertical_form) do |f| %>
										  <%= f.error_notification %>
										  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

										  <div class="form-inputs">
										    <%= f.input :name, required: true %>
										    <%= f.input :description, required: true %>
										  	<%= f.input :kind, :collection => [['visible','visible'],['hidden', 'hidden']], required: true %>
										  </div>

										  <div class="form-actions">
										    <%= f.button :submit, "Update Widget", class:"btn-primary" %>
										  </div>
										<% end %>

					        </div>
					        
					      </div>
					    </div>
					  </div>
					</div>
		  	  <%= link_to 'Delete', widget_path(widget.id), class: "btn btn-danger", method: :delete %>
		  <% end %>	

	  </td>            
	  
	</tr>
<% end %>	    

app/views/widgets/new.html.erb
<div class = "row">
	<div class= "col-lg-3">
	</div>
	<div class = "col-lg-6">
		<%= render "form" , widget: @widget%>
	</div>
</div>